Document: libfmime
Title: Debian libfmime Manual
Author: <insert document author here>
Abstract: This manual describes what libfmime is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfmime/libfmime.sgml.gz

Format: postscript
Files: /usr/share/doc/libfmime/libfmime.ps.gz

Format: text
Files: /usr/share/doc/libfmime/libfmime.text.gz

Format: HTML
Index: /usr/share/doc/libfmime/html/index.html
Files: /usr/share/doc/libfmime/html/*.html

  
